/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wishlistapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author jadef
 */
public class WishListGUI extends javax.swing.JFrame {
    private ArrayList <WishList> wishList;
    private int number = 1;

    /**
     * Creates new form WishListGUI
     */
    public WishListGUI() {
        initComponents();
        wishList = new ArrayList<>();
        descriptionLbl.setVisible(false);
        descriptionTf.setVisible(false);
        priceLbl.setVisible(false);
        priceTf.setVisible(false);
        urlLbl.setVisible(false);
        urlTf.setVisible(false);
        typeCSLbl.setVisible(false);
        typeCSTf.setVisible(false);
        brandLbl.setVisible(false);
        brandTf.setVisible(false);
        colourLbl.setVisible(false);
        colourTf.setVisible(false);
        nameLbl.setVisible(false);
        nameTf.setVisible(false);
        typeTLbl.setVisible(false);
        typeTTf.setVisible(false);
        storeLbl.setVisible(false);
        storeTf.setVisible(false);
        yearOfExpLbl.setVisible(false);
        yearOfExpTf.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGroup = new javax.swing.ButtonGroup();
        jColorChooser1 = new javax.swing.JColorChooser();
        titleLbl = new javax.swing.JLabel();
        craftSuppliesRb = new javax.swing.JRadioButton();
        toyRb = new javax.swing.JRadioButton();
        voucherRb = new javax.swing.JRadioButton();
        descriptionLbl = new javax.swing.JLabel();
        descriptionTf = new javax.swing.JTextField();
        priceLbl = new javax.swing.JLabel();
        priceTf = new javax.swing.JTextField();
        urlLbl = new javax.swing.JLabel();
        urlTf = new javax.swing.JTextField();
        typeCSLbl = new javax.swing.JLabel();
        typeCSTf = new javax.swing.JTextField();
        brandLbl = new javax.swing.JLabel();
        colourTf = new javax.swing.JTextField();
        colourLbl = new javax.swing.JLabel();
        brandTf = new javax.swing.JTextField();
        nameLbl = new javax.swing.JLabel();
        typeTTf = new javax.swing.JTextField();
        typeTLbl = new javax.swing.JLabel();
        storeTf = new javax.swing.JTextField();
        storeLbl = new javax.swing.JLabel();
        nameTf = new javax.swing.JTextField();
        yearOfExpLbl = new javax.swing.JLabel();
        yearOfExpTf = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        loadBtn = new javax.swing.JButton();
        totalCostBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(700, 300));

        titleLbl.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        titleLbl.setText("Wish List");

        typeGroup.add(craftSuppliesRb);
        craftSuppliesRb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        craftSuppliesRb.setText("Craft Supplies");
        craftSuppliesRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                craftSuppliesRbActionPerformed(evt);
            }
        });

        typeGroup.add(toyRb);
        toyRb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toyRb.setText("Toy");
        toyRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toyRbActionPerformed(evt);
            }
        });

        typeGroup.add(voucherRb);
        voucherRb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        voucherRb.setText("Voucher");
        voucherRb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voucherRbActionPerformed(evt);
            }
        });

        descriptionLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descriptionLbl.setText("Description:");

        priceLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceLbl.setText("Price:");

        urlLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        urlLbl.setText("Url:");

        typeCSLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeCSLbl.setText("Type:");

        brandLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        brandLbl.setText("Brand:");

        colourLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colourLbl.setText("Colour:");

        nameLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLbl.setText("Name:");

        typeTLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        typeTLbl.setText("Type:");

        storeLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        storeLbl.setText("Store:");

        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });

        yearOfExpLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yearOfExpLbl.setText("Year Of Expiry:");

        addBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        displayBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        searchBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        loadBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loadBtn.setText("Load");
        loadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBtnActionPerformed(evt);
            }
        });

        totalCostBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalCostBtn.setText("Total Cost");
        totalCostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCostBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(descriptionLbl)
                                    .addComponent(priceLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(urlLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(urlTf, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(descriptionTf)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(storeLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(storeTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(addBtn)
                                            .addComponent(loadBtn)
                                            .addComponent(searchBtn))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(saveBtn)
                                            .addComponent(totalCostBtn)
                                            .addComponent(displayBtn))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(brandLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(brandTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(typeCSLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(typeCSTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 4, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nameTf, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(typeTLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(typeTTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(colourLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(colourTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(yearOfExpLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearOfExpTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(voucherRb, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(craftSuppliesRb, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toyRb, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLbl)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(craftSuppliesRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(toyRb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(voucherRb)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionLbl)
                    .addComponent(descriptionTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLbl)
                    .addComponent(urlTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(urlLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeCSLbl)
                    .addComponent(typeCSTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandLbl)
                    .addComponent(colourTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colourLbl)
                    .addComponent(brandTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(typeTTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(typeTLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeLbl)
                    .addComponent(storeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearOfExpLbl)
                    .addComponent(yearOfExpTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayBtn)
                    .addComponent(addBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBtn)
                    .addComponent(saveBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadBtn)
                    .addComponent(totalCostBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void voucherRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voucherRbActionPerformed
        // TODO add your handling code here:
        descriptionLbl.setVisible(true);
        descriptionTf.setVisible(true);
        priceLbl.setVisible(true);
        priceTf.setVisible(true);
        urlLbl.setVisible(true);
        urlTf.setVisible(true);
        storeLbl.setVisible(true);
        storeTf.setVisible(true);
        yearOfExpLbl.setVisible(true);
        yearOfExpTf.setVisible(true);
        typeCSLbl.setVisible(false);
        typeCSTf.setVisible(false);
        brandLbl.setVisible(false);
        brandTf.setVisible(false);
        colourLbl.setVisible(false);
        colourTf.setVisible(false);
        nameLbl.setVisible(false);
        nameTf.setVisible(false);
        typeTLbl.setVisible(false);
        typeTTf.setVisible(false);

    }//GEN-LAST:event_voucherRbActionPerformed

    private void toyRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toyRbActionPerformed
        // TODO add your handling code here:
        descriptionLbl.setVisible(true);
        descriptionTf.setVisible(true);
        priceLbl.setVisible(true);
        priceTf.setVisible(true);
        urlLbl.setVisible(true);
        urlTf.setVisible(true);
        nameLbl.setVisible(true);
        nameTf.setVisible(true);
        typeTLbl.setVisible(true);
        typeTTf.setVisible(true);
        typeCSLbl.setVisible(false);
        typeCSTf.setVisible(false);
        brandLbl.setVisible(false);
        brandTf.setVisible(false);
        colourLbl.setVisible(false);
        colourTf.setVisible(false);
        storeLbl.setVisible(false);
        storeTf.setVisible(false);
        yearOfExpLbl.setVisible(false);
        yearOfExpTf.setVisible(false);
        
    }//GEN-LAST:event_toyRbActionPerformed

    private void craftSuppliesRbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_craftSuppliesRbActionPerformed
        // TODO add your handling code here:
        descriptionLbl.setVisible(true);
        descriptionTf.setVisible(true);
        priceLbl.setVisible(true);
        priceTf.setVisible(true);
        urlLbl.setVisible(true);
        urlTf.setVisible(true);
        typeCSLbl.setVisible(true);
        typeCSTf.setVisible(true);
        brandLbl.setVisible(true);
        brandTf.setVisible(true);
        colourLbl.setVisible(true);
        colourTf.setVisible(true);
        nameLbl.setVisible(false);
        nameTf.setVisible(false);
        typeTLbl.setVisible(false);
        typeTTf.setVisible(false);
        storeLbl.setVisible(false);
        storeTf.setVisible(false);
        yearOfExpLbl.setVisible(false);
        yearOfExpTf.setVisible(false);
        
    }//GEN-LAST:event_craftSuppliesRbActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if(craftSuppliesRb.isSelected()){
            CraftSupplies cs = new CraftSupplies();
            cs.setDescription(descriptionTf.getText());
            cs.setPrice(Double.parseDouble(priceTf.getText()));
            cs.setUrl(urlTf.getText());
            cs.setType(typeCSTf.getText());
            cs.setBrand(brandTf.getText());
            cs.setColour(colourTf.getText());
            cs.setNumber(number++);
            wishList.add(cs);
            
            
        }
        else if(toyRb.isSelected()){
            Toy t = new Toy();
            t.setDescription(descriptionTf.getText());
            t.setPrice(Double.parseDouble(priceTf.getText()));
            t.setUrl(urlTf.getText());
            t.setName(nameTf.getText());
            t.setType(typeTTf.getText());
            t.setNumber(number++);
            wishList.add(t);
            
        }
        else if(voucherRb.isSelected()){
            Voucher v = new Voucher();
            v.setDescription(descriptionTf.getText());
            v.setPrice(Double.parseDouble(priceTf.getText()));
            v.setUrl(urlTf.getText());
            v.setStore(storeTf.getText());
            v.setYearOfExp(yearOfExpTf.getText());
            v.setNumber(number++);
            wishList.add(v);
            
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < wishList.size(); i++){
            WishList wl = wishList.get(i);
            JOptionPane.showMessageDialog(null, wl.getDetails());
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        int searchTerm = Integer.parseInt(JOptionPane.showInputDialog(null, "Please enter an item number to search for"));
        
        if(wishList.size()==0){
            JOptionPane.showMessageDialog(null, "Sorry, there are no items in the list to search");
        }
        
        else if (wishList.size() < (searchTerm)){
                    JOptionPane.showMessageDialog(null, "Sorry this isn't a valid number, please try again");
                }
        else {
            
            for(WishList wl:wishList){
                if(wl.getNumber()==(searchTerm)){
                    JOptionPane.showMessageDialog(null, wl.getDetails());
                }
               
            }
        }
        
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        File f;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            f = new File("output.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(wishList);
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void loadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBtnActionPerformed
        // TODO add your handling code here:
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            f = new File("output.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);
            
            wishList = (ArrayList<WishList>)oStream.readObject();
            oStream.close();
        }
        catch(IOException | ClassNotFoundException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_loadBtnActionPerformed

    private void totalCostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCostBtnActionPerformed
        // TODO add your handling code here:
        double totalCost = 0.0;
        
       
            for(WishList wl:wishList){
                totalCost = totalCost + wl.getPrice();
            }
        
        JOptionPane.showMessageDialog(null, "The total cost of the items is "+totalCost+" euros");
       
            
        
            
        
    }//GEN-LAST:event_totalCostBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WishListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WishListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WishListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WishListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WishListGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel brandLbl;
    private javax.swing.JTextField brandTf;
    private javax.swing.JLabel colourLbl;
    private javax.swing.JTextField colourTf;
    private javax.swing.JRadioButton craftSuppliesRb;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JTextField descriptionTf;
    private javax.swing.JButton displayBtn;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JButton loadBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTf;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTf;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel storeLbl;
    private javax.swing.JTextField storeTf;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton totalCostBtn;
    private javax.swing.JRadioButton toyRb;
    private javax.swing.JLabel typeCSLbl;
    private javax.swing.JTextField typeCSTf;
    private javax.swing.ButtonGroup typeGroup;
    private javax.swing.JLabel typeTLbl;
    private javax.swing.JTextField typeTTf;
    private javax.swing.JLabel urlLbl;
    private javax.swing.JTextField urlTf;
    private javax.swing.JRadioButton voucherRb;
    private javax.swing.JLabel yearOfExpLbl;
    private javax.swing.JTextField yearOfExpTf;
    // End of variables declaration//GEN-END:variables
}
